// Extracts the Lucide icons used by the TEN10 app UI into film/icons.js
// (inner SVG markup only, so the film can inline them with any size/colour).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dir = path.join(root, "node_modules/lucide-static/icons");
const names = [
  "house", "circle-plus", "table", "chart-pie", "book", "settings", "info", "globe",
  "wallet", "credit-card", "hand-coins", "scale", "badge-plus", "calendar", "calendar-days",
  "upload", "download", "file-spreadsheet", "file-text", "circle-check", "check", "repeat",
  "mail", "send", "message-square-plus", "search", "arrow-left", "arrow-right", "x",
  "book-open", "bell", "chevron-down", "ellipsis", "arrow-left-right", "chevrons-up-down",
  "list-filter", "refresh-cw",
  "cloud", "wifi-off", "hard-drive", "monitor", "smartphone", "lock", "lightbulb", "trending-up",
  "chart-column", "list", "circle-alert", "minus", "square", "user-round-x",
];
const out = {};
for (const n of names) {
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), "utf8");
  out[n] = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"))
    .replace(/\s+/g, " ").trim();
}
fs.writeFileSync(
  path.join(root, "film/icons.js"),
  "// Generated by tools/build-icons.mjs from lucide-static (ISC) — the icon set the TEN10 app uses.\n" +
    `window.ICONS = ${JSON.stringify(out, null, 1)};\n`,
);
console.log(`wrote ${names.length} icons`);
