// Localised copy + illustrative data for both language versions.
//
// Rules this file follows (see the production brief):
// - UI strings are the app's own strings (public/locales/*), so every screen reads
//   exactly like the product.
// - Every amount is internally consistent with how TEN10 computes balances:
//     maaser  = 10% of regular income, chomesh = 20% of income flagged "calculate chomesh",
//     overall = maaser + chomesh − donations.
// - Currency is contextual: ₪ in Hebrew, $ in English. Never a feature on its own.
(function () {
  const he = {
    lang: "he",
    dir: "rtl",
    locale: "he-IL",
    currency: "ILS",
    // Kinetic typography (copy pool from the brief; used selectively)
    copy: {
      eyebrow: "מעשר כספים",
      sounds: ["זה", "נשמע", "פשוט."],
      but: "אבל…",
      // slogans next to the logo are the app's own (landing.json hero.badge / hero.tagline)
      orderTag: ["ניהול מעשרות", "ותקציב פיננסי חכם"],
      maaserLines: ["מעשר.", "חומש.", "הכל במקום אחד."],
      importLines: ["מייבאים תנועות.", "ממשיכים משם."],
      recurringLines: ["הוראות קבע —", "אוטומטית."],
      remindLines: ["וגם תזכורות", "כשצריך."],
      analyticsLines: ["ניתוח נתונים", "לכלכלת הבית."],
      reportsLines: ["הדפסת דוחות", "וייצוא נתונים."],
      // landing.json → about (partnership + endorsements)
      trust: { line1: "פותח בשיתוף עם מכון תורת האדם לאדם", line1V: ["פותח בשיתוף עם", "מכון תורת האדם לאדם"], line2: "ובהסכמת רבנים מובילים", verified: "מאושר הלכתית", endCredit: "בשיתוף מכון תורת האדם לאדם" },
      platformsTitle: "בחר את הגרסה המתאימה לך",
      halachaLine: "מאגר הלכות",
      questionLine: "שאלה שלא מצאת עליה תשובה?",
      rabbiLine: "שאל את הרב",
      togetherLine: "כל מה שצריך לניהול מעשר וחומש.",
      tagline: ["ניהול מעשרות ותקציב פיננסי,", "פשוט ומדויק."],
      free: "חינם לשימוש אישי",
      freeSub: "באתר ובתוכנה למחשב",
      url: "ten10-app.com",
      // "symbols" cut (no app screens): captions inside the ring
      sym: { imported: "תנועות יובאו", file: "תנועות.xlsx", monthly: "כל חודש", household: "הוצאות הבית", other: "אחר" },
      // "cine" cut: chapter marks, and how many narration words stay small before the key words slam in
      cine: { chapters: { import: "ייבוא", recurring: "הוראות קבע", reminders: "תזכורות", analytics: "ניתוח נתונים" },
        split: { import: 2, recurring: 3, reminders: 1, analytics: 4 }, brand: "TEN10 · ניהול מעשרות", balance: "יתרה למעשרות",
        // geo film: [first, last) narration word indices set large; the rest stay small
        big: { hook1: [0, 3], complex2: [2, 4], maaser: [4, 8], reports: [1, 3], notjust: [2, 5], halacha: [0, 2], rabbi: [6, 9], together: [0, 2], tagline: [4, 6] },
        lead: "אבל כשמצטברים",
        scenes: { hook: "מעשר", chaos: "המורכבות", order: "TEN10", maaser: "מעשר וחומש", reports: "דוחות וייצוא", halacha: "מאגר ההלכות", rabbi: "שאל את הרב", trust: "שיתוף והסכמה", platforms: "אתר ותוכנה", together: "תמונה אחת" },
        income: "הכנסות", donations: "תרומות", expenses: "חיובים", formula: "מעשר + חומש − תרומות", seen: "₪" },
    },
    // Narration words (as they appear in script.he.json) that trigger visual beats
    beats: {
      income: ["complex1", "הכנסות"],
      donations: ["complex1", "תרומות"],
      months: ["complex1", "חודשים"],
      obligations: ["complex1", "חיובים"],
      recurring: ["complex1", "והוראות"],
      harder: ["complex2", "פחות"],
      maaser: ["maaser", "מעשר"],
      chomesh: ["maaser", "חומש"],
      importWord: ["import", "לייבא"],
      existingWord: ["import", "קיימות"],
      recurringWord: ["recurring", "הוראות"],
      autoWord: ["recurring", "אוטומטית"],
      remindWord: ["reminders", "תזכורות"],
      numbers: ["notjust", "מספרים"],
      halachaWord: ["halacha", "ההלכות"],
      questionWord: ["rabbi", "שאלה"],
      rabbiWord: ["rabbi", "שאל"],
      tIncome: ["together", "ההכנסות"],
      tDonations: ["together", "התרומות"],
      tObligations: ["together", "והחיובים"],
      currencies: ["complex1", "מטבעות"],
      anyCurrency: ["maaser", "מטבע"],
      analyticsWord: ["analytics", "ניתוח"],
      moneyWord: ["analytics", "הכסף"],
      householdWord: ["analytics", "הבית"],
      webWord: ["platforms", "באתר"],
      desktopWord: ["platforms", "למחשב"],
      offlineWord: ["platforms", "אינטרנט"],
      freeWord: ["free", "חינם"],
      printWord: ["reports", "להדפיס"],
      excelWord: ["reports", "לאקסל"],
      trustWord: ["trust", "בשיתוף"],
      rabbisWord: ["trust", "רבנים"],
    },
    // Complexity scene (scene 2): product-like fragments
    chaos: {
      income: [
        { label: "משכורת", type: "income", amount: 10000 },
        { label: "הכנסה נוספת", type: "income", amount: 2000 },
      ],
      donations: [
        { label: "צדקה", type: "donation", amount: 180 },
        { label: "תרומה", type: "donation", amount: 400 },
      ],
      months: ["ינו׳", "פבר׳", "מרץ", "אפר׳", "מאי"],
      prevMonth: { label: "חודש קודם", amount: 240 },
      obligations: [
        { label: "מעשר", pct: "10%" },
        { label: "חומש", pct: "20%" },
      ],
      recurring: { label: "הוראת קבע", sub: "חודשי", badge: "1 / ∞" },
      newTx: "תנועה חדשה",
      // other currencies (converted automatically in the app — mentioned only in passing)
      currencies: [{ cur: "USD", amt: 250, conv: 915 }, { cur: "EUR", amt: 120, conv: 470 }, { cur: "GBP", amt: 80, conv: 370 }],
      calcs: [["10%", 10000], ["20%", 2000]],
      centerLabel: "יתרה למעשרות",
      // Running balance shown in the ring as fragments arrive:
      // income 12,000 → 10% = 1,200 · donations −580 → 620 · previous month +240 → 860
      // · chomesh on 2,000 (20% instead of 10%) +200 → 1,060 · recurring donation −360 → 700
      values: [1200, 620, 860, 1060, 700],
    },
    ui: {
      nav: ["דף הבית", "הוסף תנועה", "טבלת תנועות", "ניתוח נתונים", "הלכות", "הגדרות", "אודות"],
      welcome: "ברוכים הבאים ל-Ten10",
      welcomeSub: "נהל את התרומות, ההכנסות והוצאות שלך בקלות ובפשטות",
      ranges: ["מתחילת החודש", "מתחילת השנה", "מאז ומתמיד", "טווח מותאם"],
      cards: {
        overall: "יתרה למעשרות",
        income: "הכנסות (מתחילת החודש)",
        expenses: "הוצאות (מתחילת החודש)",
        donations: "תרומות (מתחילת החודש)",
        maaserChip: "מעשר",
        chomeshChip: "חומש",
        withChomesh: "מתוכם עם חומש",
        goal: (p) => `${p}% מהיעד הושלם`,
        ofIncome: (p) => `${p}% מתוך סך ההכנסות`,
      },
      chart: { title: "סיכום חודשי", months: ["ינו׳ 2026", "פבר׳ 2026", "מרץ 2026", "אפר׳ 2026", "מאי 2026"], legend: ["הכנסות", "הוצאות", "תרומות"] },
      // Add-transaction fragment used for the chomesh beat
      form: { type: "סוג התנועה", income: "הכנסה", expense: "הוצאה", donation: "תרומה", amount: "סכום", chomesh: "לחשב חומש (20%)?", desc: "עבודה נוספת" },
      table: {
        title: "טבלת תנועות",
        export: "יצוא נתונים",
        import: "ייבוא תנועות",
        isNew: "חדש",
        showRecurring: "הצג הוראות קבע",
        search: "תיאור, קטגוריה, נמען, אמצע",
        cols: ["תאריך", "תיאור", "סכום", "סוג", "קטגוריה", "אמצעי תשלום", "הוראת קבע"],
        types: { income: "הכנסה", expense: "הוצאה", donation: "תרומה" },
      },
      importFlow: {
        file: "תנועות 2025.xlsx",
        steps: ["הכנה", "העלאה", "מיפוי עמודות", "סקירה"],
        title: "ייבוא תנועות",
        done: "12 תנועות יובאו",
      },
      recurring: {
        monthNames: ["דצמבר 2025", "ינואר 2026", "פברואר 2026", "מרץ 2026"],
        weekdays: ["א׳", "ב׳", "ג׳", "ד׳", "ה׳", "ו׳", "ש׳"],
        // day-of-week index (0 = Sunday) of the 1st of each month above
        firstDow: [1, 4, 0, 0],
        daysIn: [31, 31, 28, 31],
        day: 10,
        label: "תרומה חודשית",
        amount: 360,
        freq: "חודשי",
      },
      email: {
        from: "Ten10",
        subject: "תזכורת מעשר - נותרו 820 ₪ לתרומה",
        greeting: "ערב טוב",
        reminder: "תזכורת קצרה לעדכון המעשרות, כדי לשמור על יתרה מדויקת.",
        badge: "יתרה לתרומה",
        amount: 820,
        verification: "כדאי לוודא שהוספת את ההכנסות, ההוצאות והתרומות האחרונות.",
        cta: "לעדכון המעשרות ב־Ten10",
        slogan: "ניהול מעשרות ותקציב פיננסי פשוט ומדויק",
        reminderDay: 1,
      },
      halacha: {
        title: "הלכות מעשר כספים",
        sub: "מידע והלכות בנושא מעשר כספים וחומש",
        tabs: ["מבוא", "כללים ויסודות", "שאלות נפוצות", "תרומות הנחשבות למעשר", "הכנסות החייבות במעשר", "הוצאות המוכרות למעשר", "חומש"],
        // [tab index, article] shown while browsing
        articles: [
          {
            tab: 0,
            title: "מבוא להלכות מעשר כספים",
            sub: "מידע יסודי והנחיה מעשית בהלכות מעשר כספים וחומש לפי פסקי הפוסקים",
            h: "על מדריך זה",
            p: "לבקשת רבים, צירפנו מדריך הלכתי מעשי. הרעיון שעליו מבוסס המדריך הוא למסור כללים על רגל אחת, מוסברים במיטב הגיון בצירוף דוגמאות והמחשות.",
            box: "מהות מעשר כספים והבסיס ההלכתי",
          },
          {
            tab: 4,
            title: "הכנסות החייבות במעשר",
            sub: "אילו הכנסות חייבות בהפרשת מעשר, ומה הדין בהכנסות מיוחדות",
            h: "כלל ההכנסות",
            p: "משכורת, רווחי עסק, מתנות ומענקים — לכל סוג הכנסה יש כללים משלו. כאן מרוכזים הדינים העיקריים עם דוגמאות מעשיות.",
            box: "הכנסות מן הצד ומתנות",
          },
          {
            tab: 6,
            title: "כללי הפרשת חומש לצדקה",
            sub: "הלכות והנחיות מעשיות להפרשת חומש (20%) מההכנסות לצדקה - מצוה מן המובחר",
            h: "על הפרשת חומש",
            p: "ישנם המהדרים להפריש חומש - 20% מכל הכנסותיהם לצדקה. מוסרים בשם הגר\"א זצ\"ל וגדולים נוספים שהפרשת מעשר מסוגלת לפרנסה בשפע, והפרשת חומש מסוגלת לעשירות.",
            box: "המקור להפרשת חומש",
          },
        ],
      },
      analytics: {
        title: "ניתוח נתונים",
        sub: "תובנות פיננסיות מבוססות על הנתונים שלך",
        exportPdf: "ייצוא PDF",
        // income 12,000 · expenses 7,340 · donations 580 → savings (12,000 − 7,340 − 580) / 12,000 = 34.0%
        kpis: [["שיעור חיסכון", 34.0, "%"], ["הוצאות קבועות", 66.6, "%"], ["שינוי הכנסות", 8.2, "%"]],
        insightsTitle: "תובנות",
        insights: ["שיעור חיסכון של 34.0% — מצוין!", "67% מהוצאותיך קבועות — קל לתכנן קדימה", "הכנסותיך עלו ב-8.2% לעומת התקופה הקודמת"],
        ringsTitle: "קבוע מול חד-פעמי לפי סוג",
        ringsSub: "כמה מכל סוג מגיע מהוראות קבע",
        rings: [["הוצאות", 67, 7340, "#dc2626"], ["הכנסות", 83, 12000, "#11676a"], ["תרומות", 62, 580, "#eab308"]],
        catTitle: "פירוט קטגוריות", catTabs: ["הוצאות", "הכנסות"],
        cats: [["דיור", 4889], ["מזון", 1120], ["ביגוד", 435], ["חינוך", 420], ["רכב", 312], ["כללי", 164]],
        payTitle: "אמצעי תשלום", paySub: "חלוקת הוצאות לפי אמצעי תשלום",
        pays: [["אשראי", 2451], ["העברה בנקאית", 4500], ["מזומן", 389]],
        recTitle: "נמעני תרומות", recSub: "Top נמענים בתקופה הנבחרת",
        recs: [["תרומה חודשית", 360], ["כולל ערב", 100], ["קופת צדקה", 70], ["גמ״ח שכונתי", 50]],
      },
      report: { title: "דוח תנועות", meta: "כל התאריכים | הופק בתאריך: 19/12/2025 15:50", showing: "מציג 12 מתוך 12 תנועות",
        cols: ["תאריך", "סוג", "סכום", "פרטים", "קטגוריה", "הוראת קבע"], export: "יצוא נתונים" },
      platforms: {
        web: { title: "גרסת אתר", sub: "גישה מכל מקום עם סנכרון בענן", url: "ten10-app.com",
          feats: [["globe", "גישה מכל דפדפן"], ["cloud", "סנכרון אוטומטי בענן"], ["smartphone", "ניתן להתקין כאפליקציה"]] },
        desktop: { title: "תוכנה למחשב", sub: "עבודה ללא חיבור לאינטרנט עם ביצועים מקסימליים",
          feats: [["wifi-off", "עבודה ללא אינטרנט"], ["hard-drive", "כל הנתונים נשמרים על המחשב עצמו"], ["user-round-x", "ללא צורך ברישום או הרשמה"]] },
      },
      contact: {
        title: "צור קשר",
        desc: "בחר למי ברצונך לפנות. נחזור אליך בהקדם.",
        tabs: ["פנייה לרב", "פנייה לצוות הפיתוח"],
        subjectLabel: "נושא",
        subject: "חומש ממענק חד-פעמי",
        bodyLabel: "הודעה",
        body: "קיבלתי מענק מהעבודה. האם יש להפריש ממנו חומש, או שדי במעשר?",
        submit: "שלח הודעה",
        toast: "הודעתך נשלחה בהצלחה!",
      },
    },
    // Dashboard numbers (consistent with maaser/chomesh rules above)
    data: {
      incomeBase: 10000, chomeshIncome: 2000, expenses: 7340, donations: 580,
      // before chomesh income: maaser 1000 - 580 = 420; after: chomesh 400 → overall 820
    },
    // Rows used by the import/recurring scenes (dd.mm.yyyy, as the app shows)
    rows: [
      { d: "01.12.2025", desc: "משכורת", amt: 10000, type: "income", cat: "משכורת", pay: "העברה בנקאית" },
      { d: "02.12.2025", desc: "גמ״ח שכונתי", amt: 50, type: "donation", cat: "צדקה", pay: "ביט/פייבוקס" },
      { d: "03.12.2025", desc: "קניות סופר", amt: 501, type: "expense", cat: "מזון", pay: "אשראי" },
      { d: "04.12.2025", desc: "חשמל", amt: 389, type: "expense", cat: "דיור", pay: "הוראת קבע" },
      { d: "06.12.2025", desc: "קופת צדקה", amt: 70, type: "donation", cat: "צדקה", pay: "מזומן" },
      { d: "07.12.2025", desc: "עבודה נוספת", amt: 2000, type: "income", cat: "פרילנס", pay: "העברה בנקאית" },
      { d: "08.12.2025", desc: "חוגים", amt: 420, type: "expense", cat: "חינוך", pay: "אשראי" },
      { d: "10.12.2025", desc: "תרומה חודשית", amt: 360, type: "donation", cat: "צדקה", pay: "אשראי", rec: "1 / ∞", recurring: true },
      { d: "11.12.2025", desc: "ביטוח רכב", amt: 312, type: "expense", cat: "רכב", pay: "אשראי" },
      { d: "12.12.2025", desc: "כולל ערב", amt: 100, type: "donation", cat: "צדקה", pay: "העברה בנקאית" },
      { d: "14.12.2025", desc: "ספרים", amt: 164, type: "expense", cat: "כללי", pay: "אשראי" },
      { d: "15.12.2025", desc: "שכר דירה", amt: 4500, type: "expense", cat: "דיור", pay: "העברה בנקאית", rec: "1 / ∞" },
    ],
  };

  const en = {
    lang: "en",
    dir: "ltr",
    locale: "en-US",
    currency: "USD",
    copy: {
      eyebrow: "Maaser Kesafim",
      sounds: ["Sounds", "simple."],
      but: "But…",
      orderTag: ["Smart Tithe and", "Financial Budget Management"],
      maaserLines: ["Maaser.", "Chomesh.", "One clear system."],
      importLines: ["Import your transactions.", "Continue from there."],
      recurringLines: ["Recurring transactions —", "automatic."],
      remindLines: ["And reminders", "when you need them."],
      analyticsLines: ["Analytics", "for your household budget."],
      reportsLines: ["Print reports", "and export your data."],
      trust: { line1: "Developed in partnership with Torat Ha’adam La’adam Institute", line1V: ["Developed in partnership with", "Torat Ha’adam La’adam Institute"], line2: "and endorsed by leading rabbis", verified: "Halachically Verified", endCredit: "In partnership with Torat Ha’adam La’adam Institute" },
      platformsTitle: "Choose the Right Version for You",
      halachaLine: "Halachic Library",
      questionLine: "Still have a question?",
      rabbiLine: "Ask the Rabbi",
      togetherLine: "Everything you need to manage Maaser and Chomesh.",
      tagline: ["Simple and Accurate Tithe", "and Financial Budget Management"],
      free: "Free for personal use",
      freeSub: "On the web and as desktop software",
      url: "ten10-app.com",
      sym: { imported: "transactions imported", file: "transactions.xlsx", monthly: "every month", household: "household spending", other: "Other" },
      cine: { chapters: { import: "Import", recurring: "Recurring", reminders: "Reminders", analytics: "Analytics" },
        split: { import: 1, recurring: 1, reminders: 2, analytics: 5 }, brand: "TEN10 · Maaser management", balance: "Overall Required",
        big: { hook1: [0, 3], complex2: [3, 7], maaser: [5, 8], reports: [0, 2], notjust: [3, 6], halacha: [2, 4], rabbi: [8, 11], together: [5, 7], tagline: [0, 3] },
        lead: "But once you add",
        scenes: { hook: "Maaser", chaos: "Complexity", order: "TEN10", maaser: "Maaser & Chomesh", reports: "Reports & export", halacha: "Halachic Library", rabbi: "Ask the Rabbi", trust: "Partnership", platforms: "Web & desktop", together: "One picture" },
        income: "Income", donations: "Donations", expenses: "Obligations", formula: "maaser + chomesh − donations", seen: "$" },
    },
    beats: {
      income: ["complex1", "income"],
      donations: ["complex1", "donations"],
      months: ["complex1", "months"],
      obligations: ["complex1", "commitments"],
      recurring: ["complex1", "recurring"],
      harder: ["complex2", "harder"],
      maaser: ["maaser", "Maaser"],
      chomesh: ["maaser", "Chomesh"],
      importWord: ["import", "Import"],
      existingWord: ["import", "existing"],
      recurringWord: ["recurring", "recurring"],
      autoWord: ["recurring", "entries"],
      remindWord: ["reminders", "reminders"],
      numbers: ["notjust", "numbers"],
      halachaWord: ["halacha", "Halachic"],
      questionWord: ["rabbi", "question"],
      rabbiWord: ["rabbi", "Ask"],
      tIncome: ["together", "income"],
      tDonations: ["together", "donations"],
      tObligations: ["together", "obligations"],
      currencies: ["complex1", "currencies"],
      anyCurrency: ["maaser", "currency"],
      analyticsWord: ["analytics", "analytics"],
      moneyWord: ["analytics", "money"],
      householdWord: ["analytics", "household"],
      webWord: ["platforms", "web"],
      desktopWord: ["platforms", "desktop"],
      offlineWord: ["platforms", "offline"],
      freeWord: ["free", "Free"],
      printWord: ["reports", "Print"],
      excelWord: ["reports", "Excel"],
      trustWord: ["trust", "Institute"],
      rabbisWord: ["trust", "rabbis"],
    },
    chaos: {
      income: [
        { label: "Salary", type: "income", amount: 6500 },
        { label: "Side income", type: "income", amount: 1500 },
      ],
      donations: [
        { label: "Tzedakah", type: "donation", amount: 150 },
        { label: "Donation", type: "donation", amount: 250 },
      ],
      months: ["Jan", "Feb", "Mar", "Apr", "May"],
      prevMonth: { label: "Previous month", amount: 180 },
      obligations: [
        { label: "Maaser", pct: "10%" },
        { label: "Chomesh", pct: "20%" },
      ],
      recurring: { label: "Recurring", sub: "Monthly", badge: "1 / ∞" },
      newTx: "New transaction",
      currencies: [{ cur: "EUR", amt: 120, conv: 130 }, { cur: "ILS", amt: 500, conv: 137 }, { cur: "GBP", amt: 80, conv: 101 }],
      calcs: [["10%", 6500], ["20%", 1500]],
      centerLabel: "Overall Required",
      // income 8,000 → 800 · donations −400 → 400 · previous month +180 → 580
      // · chomesh on 1,500 +150 → 730 · recurring donation −100 → 630
      values: [800, 400, 580, 730, 630],
    },
    ui: {
      nav: ["Home", "Add Transaction", "Data Table", "Analytics", "Laws", "Settings", "About"],
      welcome: "Welcome to Ten10",
      welcomeSub: "Manage your donations, income, and expenses easily and simply",
      ranges: ["From start of month", "From start of year", "All time", "Custom range"],
      cards: {
        overall: "Overall Required",
        income: "Income (From start of month)",
        expenses: "Expenses (From start of month)",
        donations: "Donations (From start of month)",
        maaserChip: "Ma'aser",
        chomeshChip: "Chomesh",
        withChomesh: "including chomesh",
        goal: (p) => `${p}% of goal completed`,
        ofIncome: (p) => `${p}% of total income`,
      },
      chart: { title: "Monthly Summary", months: ["Jan 2026", "Feb 2026", "Mar 2026", "Apr 2026", "May 2026"], legend: ["Income", "Expenses", "Donations"] },
      form: { type: "Transaction Type", income: "Income", expense: "Expense", donation: "Donation", amount: "Amount", chomesh: "Calculate Chomesh (20%)?", desc: "Side project" },
      table: {
        title: "Transactions Table",
        export: "Export Data",
        import: "Import Transactions",
        isNew: "NEW",
        showRecurring: "Show Recurring",
        search: "Description, category, re",
        cols: ["Date", "Description", "Amount", "Type", "Category", "Payment Method", "Recurring"],
        types: { income: "Income", expense: "Expense", donation: "Donation" },
      },
      importFlow: {
        file: "bank-transactions-2025.xlsx",
        steps: ["Prepare", "Upload", "Map Columns", "Review"],
        title: "Import Transactions",
        done: "12 transactions imported",
      },
      recurring: {
        monthNames: ["December 2025", "January 2026", "February 2026", "March 2026"],
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        firstDow: [1, 4, 0, 0],
        daysIn: [31, 31, 28, 31],
        day: 10,
        label: "Monthly donation",
        amount: 100,
        freq: "Monthly",
      },
      email: {
        from: "Ten10",
        subject: "Tithe reminder - $550 remaining",
        greeting: "Good evening",
        reminder: "A quick reminder to update your tithes and keep your balance accurate.",
        badge: "Due to give",
        amount: 550,
        verification: "Make sure you have added your latest income, expenses, and donations.",
        cta: "Update your tithes in Ten10",
        slogan: "Simple and Accurate Tithe and Financial Budget Management",
        reminderDay: 1,
      },
      halacha: {
        title: "<em>Halachos</em> of <em>Ma'aser Kesafim</em>",
        sub: "Information and <em>halachos</em> about <em>Ma'aser Kesafim</em> and <em>Chomesh</em>",
        tabs: ["Introduction", "Principles & Foundations", "FAQ", "Donations Considered <em>Ma'aser</em>", "Income Subject to <em>Ma'aser</em>", "Recognized Expenses for <em>Ma'aser</em>", "<em>Chomesh</em>"],
        articles: [
          {
            tab: 0,
            title: "Introduction to the Laws of <em>Ma'aser Kesafim</em>",
            sub: "Fundamental information and practical guidance, according to the <em>poskim</em>",
            h: "About This Guide",
            p: "At the request of many, we have included a practical halachic guide. It presents the core principles concisely, explained clearly and accompanied by examples.",
            box: "The Essence of <em>Ma'aser Kesafim</em>",
          },
          {
            tab: 4,
            title: "Income Subject to <em>Ma'aser</em>",
            sub: "Which income requires separating <em>ma'aser</em>, and how special income is treated",
            h: "Types of Income",
            p: "Salary, business profit, gifts and grants — each kind of income has its own rules. The main <em>halachos</em> are gathered here with practical examples.",
            box: "Side Income and Gifts",
          },
          {
            tab: 6,
            title: "Rules for Separating <em>Chomesh</em> for <em>Tzedakah</em>",
            sub: "<em>Halachos</em> and practical guidance for separating <em>chomesh</em> (20%) from income for <em>tzedakah</em>",
            h: "About Separating <em>Chomesh</em>",
            p: "There are those who are meticulous to separate <em>chomesh</em> - 20% of all their income for <em>tzedakah</em>. It is transmitted in the name of the <em>Vilna Gaon</em> zt\"l and other great ones that separating <em>ma'aser</em> brings about abundant livelihood.",
            box: "The Source for Separating <em>Chomesh</em>",
          },
        ],
      },
      analytics: {
        title: "Analytics",
        sub: "Financial insights based on your data",
        exportPdf: "Export PDF",
        // income 8,000 · expenses 4,820 · donations 400 → savings (8,000 − 4,820 − 400) / 8,000 = 34.8%
        kpis: [["Savings Rate", 34.8, "%"], ["Fixed Expenses", 36.2, "%"], ["Income change", 6.5, "%"]],
        insightsTitle: "Insights",
        insights: ["Savings rate of 34.8% — excellent!", "36% of your expenses are recurring — easy to plan ahead", "Your income rose 6.5% vs. the previous period"],
        ringsTitle: "Recurring vs. One-Time by Type",
        ringsSub: "Share of standing orders per category",
        rings: [["Expenses", 36, 4820, "#dc2626"], ["Income", 81, 8000, "#11676a"], ["Donations", 25, 400, "#eab308"]],
        catTitle: "Category Breakdown", catTabs: ["Expenses", "Income"],
        cats: [["Housing", 1746], ["Food", 1480], ["Education", 640], ["Car", 420], ["Clothing", 350], ["General", 184]],
        payTitle: "Payment Methods", paySub: "Expense breakdown by payment method",
        pays: [["Credit card", 2980], ["Bank transfer", 1650], ["Cash", 190]],
        recTitle: "Donation Recipients", recSub: "Top recipients in selected period",
        recs: [["Kollel", 136], ["Food bank", 104], ["Monthly donation", 100], ["Pushka", 60]],
      },
      report: { title: "Transactions Report", meta: "All Dates | Generated on: 12/19/2025 3:50 PM", showing: "Showing 12 out of 12 transactions",
        cols: ["Date", "Type", "Amount", "Details", "Category", "Recurring"], export: "Export Data" },
      platforms: {
        web: { title: "Website Version", sub: "Access anywhere with cloud sync", url: "ten10-app.com",
          feats: [["globe", "Access from any browser"], ["cloud", "Automatic cloud sync"], ["smartphone", "Can be installed as an app"]] },
        desktop: { title: "Computer Software", sub: "Offline work with maximum performance",
          feats: [["wifi-off", "Works without internet"], ["hard-drive", "All data is saved on the computer itself"], ["user-round-x", "No registration or sign-up required"]] },
      },
      contact: {
        title: "Contact Us",
        desc: "Choose who you want to contact. We'll get back to you soon.",
        tabs: ["Contact Rabbi", "Contact Dev Team"],
        subjectLabel: "Subject",
        subject: "Chomesh on a one-time bonus",
        bodyLabel: "Message",
        body: "I received a bonus from work. Should I separate chomesh from it, or is ma'aser enough?",
        submit: "Send Message",
        toast: "Your message has been sent successfully!",
      },
    },
    data: {
      incomeBase: 6500, chomeshIncome: 1500, expenses: 4820, donations: 400,
      // before chomesh income: maaser 650 - 400 = 250; after: chomesh 300 → overall 550
    },
    rows: [
      { d: "Dec 01, 2025", desc: "Salary", amt: 6500, type: "income", cat: "Salary", pay: "Bank transfer" },
      { d: "Dec 02, 2025", desc: "Food bank", amt: 50, type: "donation", cat: "Tzedakah", pay: "Credit card" },
      { d: "Dec 03, 2025", desc: "Groceries", amt: 184, type: "expense", cat: "Food", pay: "Credit card" },
      { d: "Dec 04, 2025", desc: "Electricity", amt: 96, type: "expense", cat: "Housing", pay: "Standing order" },
      { d: "Dec 06, 2025", desc: "Pushka", amt: 18, type: "donation", cat: "Tzedakah", pay: "Cash" },
      { d: "Dec 07, 2025", desc: "Side project", amt: 1500, type: "income", cat: "Freelance", pay: "Bank transfer" },
      { d: "Dec 08, 2025", desc: "After-school", amt: 140, type: "expense", cat: "Education", pay: "Credit card" },
      { d: "Dec 10, 2025", desc: "Monthly donation", amt: 100, type: "donation", cat: "Tzedakah", pay: "Credit card", rec: "1 / ∞", recurring: true },
      { d: "Dec 11, 2025", desc: "Car insurance", amt: 88, type: "expense", cat: "Car", pay: "Credit card" },
      { d: "Dec 12, 2025", desc: "Kollel", amt: 36, type: "donation", cat: "Tzedakah", pay: "Bank transfer" },
      { d: "Dec 14, 2025", desc: "Books", amt: 42, type: "expense", cat: "General", pay: "Credit card" },
      { d: "Dec 15, 2025", desc: "Rent", amt: 1650, type: "expense", cat: "Housing", pay: "Bank transfer", rec: "1 / ∞" },
    ],
  };

  window.CONTENT = { he, en };
})();
