import { supabase } from "@/lib/supabaseClient";
import { RecurringTransaction } from "@/types/transaction";
import { getPlatform } from "../platformManager";
import { useDonationStore } from "../store";
import { nanoid } from "nanoid";
import { logger } from "@/lib/logger";
import { invokeTauri } from "@/lib/tauri-invoke";
import {
  assertBulkPatch,
  type RecurringBulkPatch,
} from "@/lib/tableTransactions/bulkActions";
import { normalizePaymentMethodValue } from "@/lib/payment-methods";
import { clearPaymentMethodCache } from "./paymentMethods.service";

// Type for creating a new recurring transaction, omitting fields generated by the DB
// For desktop, we will generate the ID on the client.
export type NewRecurringTransaction = Omit<
  RecurringTransaction,
  "id" | "user_id" | "created_at" | "updated_at" | "execution_count" | "status"
>;

/**
 * Creates a new recurring transaction definition in the database.
 * @param definition - The recurring transaction details.
 * @returns The created recurring transaction data.
 */
export async function createRecurringTransaction(
  definition: NewRecurringTransaction
): Promise<RecurringTransaction> {
  const platform = getPlatform();
  const normalizedDefinition = {
    ...definition,
    payment_method:
      normalizePaymentMethodValue(definition.payment_method) ?? undefined,
  };

  if (platform === "web") {
    // --- WEB (SUPABASE) LOGIC ---
    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      logger.error("Error getting user:", userError);
      throw new Error("User not found");
    }

    const { data, error } = await supabase
      .from("recurring_transactions")
      .insert([
        {
          ...normalizedDefinition,
          user_id: user.id,
        },
      ])
      .select()
      .single();

    if (error) {
      logger.error("Error creating recurring transaction on Supabase:", error);
      throw error;
    }
    return data;
  } else if (platform === "desktop") {
    // --- DESKTOP (TAURI) LOGIC ---
    const newRecurringTransaction: RecurringTransaction = {
      ...normalizedDefinition,
      id: nanoid(), // Generate client-side ID for desktop
      user_id: null, // No user concept on desktop
      status: "active",
      execution_count: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };

    try {
      await invokeTauri("add_recurring_transaction_handler", {
        recTransaction: newRecurringTransaction,
      });
      return newRecurringTransaction; // Return the object we just created
    } catch (error) {
      logger.error("Error creating recurring transaction on Desktop:", error);
      throw new Error(
        "Failed to save recurring transaction to desktop database."
      );
    }
  } else {
    throw new Error("Unsupported platform");
  }
}

/**
 * Fetches all recurring transactions for the currently authenticated user.
 * @returns An array of recurring transactions.
 */
export async function getRecurringTransactions(): Promise<
  RecurringTransaction[]
> {
  const { data, error } = await supabase
    .from("recurring_transactions")
    .select("*");

  if (error) {
    logger.error("Error fetching recurring transactions:", error);
    throw error;
  }

  return data || [];
}

/**
 * Fetches a single recurring transaction by its ID.
 * @param id The ID of the recurring transaction.
 * @returns A single recurring transaction object.
 */
export async function getRecurringTransactionById(
  id: string
): Promise<RecurringTransaction> {
  const platform = getPlatform();

  if (platform === "web") {
    const { data, error } = await supabase
      .rpc("get_recurring_transaction_by_id", { p_id: id })
      .single();

    if (error) {
      logger.error(
        "Error fetching recurring transaction by ID from Supabase:",
        error
      );
      throw error;
    }
    if (!data) {
      throw new Error(`Recurring transaction with ID ${id} not found.`);
    }
    return data as RecurringTransaction;
  } else if (platform === "desktop") {
    try {
      const result: RecurringTransaction = await invokeTauri(
        "get_recurring_transaction_by_id_handler",
        { id }
      );
      return result;
    } catch (error) {
      logger.error(
        "Error fetching recurring transaction by ID from Desktop:",
        error
      );
      throw new Error(
        `Failed to fetch recurring transaction with ID ${id} from desktop database.`
      );
    }
  } else {
    throw new Error("Unsupported platform");
  }
}

function validateBulkIds(ids: readonly string[]): string[] {
  if (ids.length === 0) {
    throw new Error("Bulk action requires at least one id");
  }

  const normalizedIds = ids.map((id) => id.trim());
  if (normalizedIds.some((id) => id.length === 0)) {
    throw new Error("Bulk action ids must not be empty");
  }

  if (new Set(normalizedIds).size !== normalizedIds.length) {
    throw new Error("Bulk action ids must be unique");
  }

  return normalizedIds;
}

async function getAuthenticatedUserId(): Promise<string> {
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    throw new Error("User not authenticated for Supabase operation.");
  }

  return user.id;
}

function readAffectedCount(data: unknown): number {
  if (typeof data === "number") {
    return data;
  }

  throw new Error("Bulk action did not return an affected count.");
}

function verifyAffectedCount(
  expectedCount: number,
  affectedCount: number,
): void {
  if (affectedCount !== expectedCount) {
    throw new Error(
      `Expected to affect ${expectedCount} recurring transactions, affected ${affectedCount}`,
    );
  }
}

function markBulkMutationSucceeded(): void {
  useDonationStore.getState().setLastDbFetchTimestamp(Date.now());
}

export async function bulkDeleteRecurringTransactions(
  ids: readonly string[],
): Promise<void> {
  const validatedIds = validateBulkIds(ids);
  const platform = getPlatform();

  if (platform === "web") {
    const userId = await getAuthenticatedUserId();
    const { data, error } = await supabase.rpc(
      "bulk_delete_user_recurring_transactions",
      {
        p_user_id: userId,
        p_ids: validatedIds,
      },
    );

    if (error) {
      throw error;
    }

    verifyAffectedCount(validatedIds.length, readAffectedCount(data));
    markBulkMutationSucceeded();
    clearPaymentMethodCache();
    return;
  }

  if (platform === "desktop") {
    const affectedCount = await invokeTauri<number>(
      "bulk_delete_recurring_transactions_handler",
      { ids: validatedIds },
    );
    verifyAffectedCount(validatedIds.length, affectedCount);
    markBulkMutationSucceeded();
    clearPaymentMethodCache();
    return;
  }

  throw new Error(
    "Cannot bulk delete recurring transactions: Platform not initialized.",
  );
}

export async function bulkUpdateRecurringTransactions(
  ids: readonly string[],
  patch: RecurringBulkPatch,
): Promise<void> {
  const validatedIds = validateBulkIds(ids);
  const platform = getPlatform();
  assertBulkPatch(patch);
  const updates: RecurringBulkPatch = {
    ...patch,
    payment_method:
      patch.payment_method !== undefined
        ? normalizePaymentMethodValue(patch.payment_method)
        : undefined,
  };

  if (platform === "web") {
    const userId = await getAuthenticatedUserId();
    const { data, error } = await supabase.rpc(
      "bulk_update_user_recurring_transactions",
      {
        p_user_id: userId,
        p_ids: validatedIds,
        p_updates: updates,
      },
    );

    if (error) {
      throw error;
    }

    verifyAffectedCount(validatedIds.length, readAffectedCount(data));
    markBulkMutationSucceeded();
    if (updates.payment_method !== undefined) {
      clearPaymentMethodCache();
    }
    return;
  }

  if (platform === "desktop") {
    const affectedCount = await invokeTauri<number>(
      "bulk_update_recurring_transactions_handler",
      {
        ids: validatedIds,
        updates,
      },
    );
    verifyAffectedCount(validatedIds.length, affectedCount);
    markBulkMutationSucceeded();
    if (updates.payment_method !== undefined) {
      clearPaymentMethodCache();
    }
    return;
  }

  throw new Error(
    "Cannot bulk update recurring transactions: Platform not initialized.",
  );
}
