name: Keep Supabase Alive

on:
  schedule:
    # Runs every 2 days at midnight UTC
    - cron: "0 0 */2 * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase REST API root
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" \
            "${{ secrets.SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}")

          echo "Supabase API response code: $response_code"

          # Check if the response code is in the 2xx range
          if [[ $response_code -ge 200 && $response_code -lt 300 ]]; then
            echo "Successfully pinged Supabase."
          else
            echo "Failed to ping Supabase. Response code: $response_code"
            exit 1
          fi
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
